<?php

namespace ContainerLEn5GUd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8gm2_1EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8gm2.1E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8gm2.1E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'imagesRepository' => ['privates', 'App\\Repository\\ImagesRepository', 'getImagesRepositoryService', true],
            'paragraphesRepository' => ['privates', 'App\\Repository\\ParagraphesRepository', 'getParagraphesRepositoryService', true],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'imagesRepository' => 'App\\Repository\\ImagesRepository',
            'paragraphesRepository' => 'App\\Repository\\ParagraphesRepository',
            'postRepository' => 'App\\Repository\\PostRepository',
        ]);
    }
}
