<?php

namespace Container75T4bG8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V9WkYUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v9WkY_u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v9WkY_u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'imagesRepository' => ['privates', 'App\\Repository\\ImagesRepository', 'getImagesRepositoryService', true],
        ], [
            'imagesRepository' => 'App\\Repository\\ImagesRepository',
        ]);
    }
}
