<?php

namespace Container75T4bG8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SjxRXbYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sjxRXbY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sjxRXbY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'imageRepository' => ['privates', 'App\\Repository\\ImagesRepository', 'getImagesRepositoryService', true],
        ], [
            'entityManager' => '?',
            'imageRepository' => 'App\\Repository\\ImagesRepository',
        ]);
    }
}
