<?php

namespace Container55KuC0i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_ADDyJk4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.aDDyJk4' shared service.
     *
     * @return \http\Client\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::register()": the $request argument is type-hinted with the non-existent class or interface: "http\\Client\\Request".');
    }
}
