<?php

namespace ContainerFyfVJ6w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SNmotg3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sNmotg3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sNmotg3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'postStatusRepo' => ['privates', 'App\\Repository\\PostStatusRepository', 'getPostStatusRepositoryService', true],
        ], [
            'postRepo' => 'App\\Repository\\PostRepository',
            'postStatusRepo' => 'App\\Repository\\PostStatusRepository',
        ]);
    }
}
