<?php

namespace ContainerXYiwID6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Px4d2ESService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.px4d2ES' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.px4d2ES'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored.aDDyJk4', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::register()": the $request argument is type-hinted with the non-existent class or interface: "http\\Client\\Request".'],
        ], [
            'request' => '?',
        ]);
    }
}
