<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2mVrusu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2mVrusu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2mVrusu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2mVrusu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2mVrusu\App_KernelDevDebugContainer([
    'container.build_hash' => '2mVrusu',
    'container.build_id' => '5c893d45',
    'container.build_time' => 1709062652,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2mVrusu');
