<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYLv9Cgu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYLv9Cgu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYLv9Cgu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYLv9Cgu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYLv9Cgu\App_KernelDevDebugContainer([
    'container.build_hash' => 'YLv9Cgu',
    'container.build_id' => 'dea22eef',
    'container.build_time' => 1708094906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYLv9Cgu');
