<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container55KuC0i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container55KuC0i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container55KuC0i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container55KuC0i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container55KuC0i\App_KernelDevDebugContainer([
    'container.build_hash' => '55KuC0i',
    'container.build_id' => 'dadb85f7',
    'container.build_time' => 1705582836,
], __DIR__.\DIRECTORY_SEPARATOR.'Container55KuC0i');
